/* eslint-disable sort-keys */
import { darken, transparentize } from 'polished'
import palette from './palette'

const theme = {
  palette,
  fontPrimary: "'Roboto', sans-serif",
  screenSizes: {
    sm: '48rem',
    md: '62rem',
    lg: '75rem'
  },
  brandNameColor: palette['red10'],
  buttonBackgroundColor: palette['red10'],
  buttonColor: palette['white'],
  buttonHoverColor: darken(0.05, palette['red10']),
  dataRowBackgroundColor: palette['gray1'],
  dataRowHighlightBackgroundColor: palette['white'],
  dataTableBackgroundColor: palette['gray1'],
  dataTableBorderColor: palette['gray2'],
  inputColor: palette['gray8'],
  iconColor: palette['red10'],
  iconHoverColor: darken(0.05, palette['red10']),
  inputBackgroundColor: palette['white'],
  inputBorderColor: palette['gray2'],
  inputPlaceholderColor: palette['gray3'],
  linkColor: palette['red10'],
  linkHoverColor: palette['red7'],
  listItemColor: palette['red10'],
  loaderColor: palette['red10'],
  modalBackgroundColor: transparentize(0.3, palette['gray8']),
  modalBorderColor: palette['gray3'],
  modalForegroundColor: palette['white'],
  modalTogglerColor: palette['gray8'],
  modalTogglerHoverColor: palette['red10'],
  modalZIndex: 101,
  multiSelectBackgroundColor: palette['white'],
  multiSelectBorderColor: palette['gray2'],
  multiSelectColor: palette['gray8'],
  multiSelectHoverBackgroundColor: palette['gray1'],
  multiSelectPlaceholderColor: palette['gray2'],
  navbarBrandZIndex: 100,
  navbarDropdownContentBackgroundColor: palette['white'],
  navbarDropdownContentShadowColor: palette['gray3'],
  navbarDropdownContentShadowColor2: palette['gray3'],
  navbarDropdownHeaderColor: palette['red10'],
  navbarDropdownItem: palette['red10'],
  navbarDropdownItemMobile: palette['white'],
  navbarMenuBackgroundColor: palette['red10'],
  navbarMenuZIndex: 50,
  navbarDropdownContentBorderColor: palette['white'],
  navbarTogglerColor: palette['white'],
  navbarTogglerZIndex: 100,
  panelBackgroundColor: palette['white'],
  panelShadowColor: palette['gray2'],
  quoteBackgroundColor: palette['gray1'],
  quoteBorderColor: palette['gray2'],
  quoteIconColor: palette['gray4'],
  sectionBackgroundColor: palette['gray2'],

  selectBackgroundColor: palette['white'],
  selectBorderColor: palette['gray2'],
  smultiSelectColor: palette['gray8'],
  selectHoverBackgroundColor: palette['gray1'],
  selectPlaceholderColor: palette['gray2'],

  separatorColor: palette['red10'],
  tabMenuItemColor: palette['gray8'],
  tabMenuItemBackgroundColor: palette['gray1'],
  tabMenuItemBorderColor: palette['gray2'],
  tabMenuItemSelectedColor: palette['white'],
  tabMenuItemSelectedBackgroundColor: palette['red10'],
  tabMenuItemSelectedBorderColor: palette['red10'],
  textColor: palette['gray8']
}

export default theme
/* eslint-enable sort-keys */
